[project]
name = "backend-learning"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg",
    "fastapi",
    "langchain",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.12",
    "llama-index>=0.14.25",
    "llama-index-embeddings-huggingface>=0.8.0",
    "llama-index-llms-groq>=0.6.1",
    "llama-index-readers-file>=0.7.0",
    "openai",
    "passlib[bcrypt]",
    "pydantic",
    "pymupdf>=1.28.2",
    "python-dotenv",
    "python-jose[cryptography]",
    "sentence-transformers>=6.1.0",
    "sqlacodegen",
    "sqlalchemy[asyncio]",
    "synapsekit[groq,semantic]>=2.0.1",
    "uvicorn",
]
