[project]
name = "backend-learning"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg",
    "fastapi",
    "langchain",
    "langgraph>=1.2.12",
    "openai",
    "passlib[bcrypt]",
    "pydantic",
    "python-dotenv",
    "python-jose[cryptography]",
    "sentence-transformers>=6.1.0",
    "sqlacodegen",
    "sqlalchemy[asyncio]",
    "synapsekit[groq,semantic]>=2.0.1",
    "uvicorn",
]
